name: watering_system
description: a utm project
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  auto_route: ^7.4.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_getit: ^1.2.1
  flutter_svg: ^2.0.5
  google_fonts: ^5.0.0
  http: ^1.0.0
  injectable: ^2.1.2
  intl: ^0.18.1
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
